name: CloseItemEntity
main: CloseItemEntity\CloseItemEntity
version: 1.1.0
api:
- 2.0.0
- 2.1.0
- 3.0.0-alpha8
- 3.0.0-alpha9
- 3.0.0-alpha10
- 3.0.1
load: POSTWORLD
author:
- anseEND
- GooglePlugin

commands:
  close:
    description: Clean up drops.
    aliases: ["clean","清理"]
    permission: CloseItemEntity.command
permissions:
  CloseItemEntity.command:
    description: 
    default: op